### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by madnessJs** [Vodkamishka/hotel#10]
1. Разнеси зависимости на devDep и dep
dependencies - зависимости без которых не может обойтись проект
devDependencies - зависимости без которых может обойтись проект
2. Пропиши скрипт для линтирования проекта

**Comment by Vodkamishka** [comment]
> 1. Разнеси зависимости на devDep и dep
>    dependencies - зависимости без которых не может обойтись проект
>    devDependencies - зависимости без которых может обойтись проект
> 2. Пропиши скрипт для линтирования проекта

Исправил

**Comment by madnessJs** [comment]
1. Что за свойство index в файле?)
2. Нужно добавить св-во private

**Comment by Vodkamishka** [comment]
> 1. Что за свойство index в файле?)
> 2. Нужно добавить св-во private

исправил

**Comment by madnessJs** [comment]
> > 1. Что за свойство index в файле?)
> > 2. Нужно добавить св-во private
> 
> исправил

при исправлениях ссылайся плиз на номер issue

**Comment by madnessJs** [comment]
Не вижу св-ва private

**Comment by madnessJs** [comment]
1. Именуй нормально коммиты, описывай что конкретно делал
2. Один коммит = одно исправление
3. В каждом исправлении ссылайся на номер issue
Хорошо?

**Comment by Vodkamishka** [comment]
> 1. Не вижу св-ва private
> 2. Зачем 2 разные dev сборки?
>    ![image](https://user-images.githubusercontent.com/46949445/76741253-4fc4e500-6780-11ea-99b0-9505dc9297f3.png)
> 
> Также убери поля name, version, keywords

Исправил

**Comment by Vodkamishka** [comment]
> 1. Именуй нормально коммиты, описывай что конкретно делал
> 2. Один коммит = одно исправление
> 3. В каждом исправлении ссылайся на номер issue
> 
> Хорошо?

Хорошо

**Comment by madnessJs** [comment]
Расположи в порядке private, author, lisence, а уже потом скрипты и зависимости

**Comment by Vodkamishka** [comment]
> Расположи в порядке private, author, lisence, а уже потом скрипты и зависимости

Исправил
