### ISSUE TITLE
Перевод строки crlf => lf

### ISSUE THREAD

**Issue by madnessJs** [Vodkamishka/hotel#12]
Лучше использовать lf окончания строк
![image](https://user-images.githubusercontent.com/46949445/77403324-2419ae80-6dc1-11ea-85cc-d4a12a3a089d.png)

**Comment by Vodkamishka** [comment]
> Лучше использовать lf окончания строк
> ![image](https://user-images.githubusercontent.com/46949445/77403324-2419ae80-6dc1-11ea-85cc-d4a12a3a089d.png)

исправил
