### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by madnessJs** [Vodkamishka/hotel#9]
1. Указать нормальное название проекта (и на github и в реадме, везде). hotel-webpack-pug-scss - набор слов
2. Тут тоже как-то не понятно написано и кавычки какие-то
![image](https://user-images.githubusercontent.com/46949445/76319646-9209a480-62f0-11ea-80fe-494f929097e9.png)
![image](https://user-images.githubusercontent.com/46949445/76319688-9fbf2a00-62f0-11ea-80c8-f601f3976534.png)
3. Для вставок кода есть специальные теги в markdown, тоже поправь этот момент
4. Лучше написать build
![image](https://user-images.githubusercontent.com/46949445/76319828-d72dd680-62f0-11ea-8b2d-323352cdaf40.png)

**Comment by Vodkamishka** [comment]
> 1. Указать нормальное название проекта (и на github и в реадме, везде). hotel-webpack-pug-scss - набор слов
> 2. Тут тоже как-то не понятно написано и кавычки какие-то
>    ![image](https://user-images.githubusercontent.com/46949445/76319646-9209a480-62f0-11ea-80fe-494f929097e9.png)
>    ![image](https://user-images.githubusercontent.com/46949445/76319688-9fbf2a00-62f0-11ea-80c8-f601f3976534.png)
> 3. Для вставок кода есть специальные теги в markdown, тоже поправь этот момент
> 4. Лучше написать build
>    ![image](https://user-images.githubusercontent.com/46949445/76319828-d72dd680-62f0-11ea-8b2d-323352cdaf40.png)

Исправил

**Comment by madnessJs** [comment]
1. Вот, посмотри как вставляются примеры кода в markdown
![image](https://user-images.githubusercontent.com/46949445/76739836-dc21d880-677d-11ea-9763-88930c94dac0.png)
2. Название проекта не везде исправил
![image](https://user-images.githubusercontent.com/46949445/76739886-f5c32000-677d-11ea-9422-86418522e1f1.png)
и еще посмотри, это не все)
3. Зачем ссылка на репозиторий внутри репозитория?)
![image](https://user-images.githubusercontent.com/46949445/76739927-12f7ee80-677e-11ea-8c74-b0ae9a85b3b8.png)
4. Если хочешь добавить макет задания, то лучше указать. Макет задания и ссылка
![image](https://user-images.githubusercontent.com/46949445/76740384-dd073a00-677e-11ea-87ef-186b3c3c13b8.png)
5. Указать все доступные способы клонирования
![image](https://user-images.githubusercontent.com/46949445/76740431-edb7b000-677e-11ea-9bd4-667d33a872ae.png)
6. Тут лучше обозвать prod и dev сборка, например
![image](https://user-images.githubusercontent.com/46949445/76740533-193a9a80-677f-11ea-9afb-16e7c4fbabc7.png)

**Comment by Vodkamishka** [comment]
> 1. Вот, посмотри как вставляются примеры кода в markdown
>    ![image](https://user-images.githubusercontent.com/46949445/76739836-dc21d880-677d-11ea-9763-88930c94dac0.png)
> 2. Название проекта не везде исправил
>    ![image](https://user-images.githubusercontent.com/46949445/76739886-f5c32000-677d-11ea-9422-86418522e1f1.png)
>    и еще посмотри, это не все)
> 3. Зачем ссылка на репозиторий внутри репозитория?)
>    ![image](https://user-images.githubusercontent.com/46949445/76739927-12f7ee80-677e-11ea-8c74-b0ae9a85b3b8.png)
> 4. Если хочешь добавить макет задания, то лучше указать. Макет задания и ссылка
>    ![image](https://user-images.githubusercontent.com/46949445/76740384-dd073a00-677e-11ea-87ef-186b3c3c13b8.png)
> 5. Указать все доступные способы клонирования
>    ![image](https://user-images.githubusercontent.com/46949445/76740431-edb7b000-677e-11ea-9bd4-667d33a872ae.png)
> 6. Тут лучше обозвать prod и dev сборка, например
>    ![image](https://user-images.githubusercontent.com/46949445/76740533-193a9a80-677f-11ea-9afb-16e7c4fbabc7.p

> 1. Вот, посмотри как вставляются примеры кода в markdown
>    ![image](https://user-images.githubusercontent.com/46949445/76739836-dc21d880-677d-11ea-9763-88930c94dac0.png)
> 2. Название проекта не везде исправил
>    ![image](https://user-images.githubusercontent.com/46949445/76739886-f5c32000-677d-11ea-9422-86418522e1f1.png)
>    и еще посмотри, это не все)
> 3. Зачем ссылка на репозиторий внутри репозитория?)
>    ![image](https://user-images.githubusercontent.com/46949445/76739927-12f7ee80-677e-11ea-8c74-b0ae9a85b3b8.png)
> 4. Если хочешь добавить макет задания, то лучше указать. Макет задания и ссылка
>    ![image](https://user-images.githubusercontent.com/46949445/76740384-dd073a00-677e-11ea-87ef-186b3c3c13b8.png)
> 5. Указать все доступные способы клонирования
>    ![image](https://user-images.githubusercontent.com/46949445/76740431-edb7b000-677e-11ea-9bd4-667d33a872ae.png)
> 6. Тут лучше обозвать prod и dev сборка, например
>    ![image](https://user-images.githubusercontent.com/46949445/76740533-193a9a80-677f-11ea-9afb-16e7c4fbabc7.png)

Исправил

**Comment by madnessJs** [comment]
1. [click](https://gist.github.com/Jekins/2bf2d0638163f1294637#Code)
2. 
![image](https://user-images.githubusercontent.com/46949445/76858898-5ed39200-6869-11ea-8d17-af51829bab50.png)
3. Не указано название 1-го способа
![image](https://user-images.githubusercontent.com/46949445/76858987-7e6aba80-6869-11ea-9192-3a04a5114460.png)
4. Скрипты должны выполняться npm run *script name*
![image](https://user-images.githubusercontent.com/46949445/76859101-b1ad4980-6869-11ea-9cd4-8355b44e4ac0.png)

**Comment by Vodkamishka** [comment]
> 1. [click](https://gist.github.com/Jekins/2bf2d0638163f1294637#Code)
> 
> ![image](https://user-images.githubusercontent.com/46949445/76858898-5ed39200-6869-11ea-8d17-af51829bab50.png)
> 3. Не указано название 1-го способа
> ![image](https://user-images.githubusercontent.com/46949445/76858987-7e6aba80-6869-11ea-9192-3a04a5114460.png)

исправил

**Comment by madnessJs** [comment]
Это пример кода также
![image](https://user-images.githubusercontent.com/46949445/77403492-56c3a700-6dc1-11ea-9910-afad4a8e109e.png)

**Comment by Vodkamishka** [comment]
Исправил

**Comment by Vodkamishka** [comment]
> Это пример кода также
> ![image](https://user-images.githubusercontent.com/46949445/77403492-56c3a700-6dc1-11ea-9910-afad4a8e109e.png)

исправил
